version: '3.8'

services:

    db:
        image: 'mysql:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: Mythi@2024
            MYSQL_USER: myuser
            MYSQL_PASSWORD: mypassword

        ports:
            - '3306:3306'
        volumes:
            - ./mysql-init-db:/docker-entrypoint-initdb.d

    minioservice:
        image: minio/minio:latest
        volumes:
            - minio-data:/data
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        command: server /data --console-address :9001

    fileservice:
        build: ./fileservice
        ports:
            - "8081:8080"
        depends_on:
            - minioservice

    authservice:
        build: ./authservice
        ports:
            - "8080:8080"
        depends_on:
            - db

    uploadservice:
        build: ./video_uploader
        ports:
            - "8082:8080"
        depends_on:
            - fileservice
            - db

    streamservice:
        build: ./video_streamer
        ports:
            - "8083:8080"
        depends_on:
            - db



volumes:
    minio-data:
