version: '3.8'

services:

    authservice:
        build: ./authservice
        ports:
            - "8080:8080"
        depends_on:
            - db

    db:
        image: 'mysql:8.0'
        environment:
            MYSQL_DATABASE: authservice_db
            MYSQL_ROOT_PASSWORD: Mythi@2024
            MYSQL_USER: myuser
            MYSQL_PASSWORD: mypassword

        ports:
            - '3306:3306'
        volumes:
            - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
    db-data:
